let suggestions =[
    "Amritsar",	
    "Allahabad",
    "BADRINATH",	
    "BALASINOR",	
    "BANGALORE",
    "BARBIL	",
    "BAREILLY",
    "Coimbatore",
    "Chennai",
    "DAMAN",
    "DANDELI",
    "DAPOLI",
    "DARJEELING",
    "DAUSA",
    "DEHRADUN",
    "FIROZABAD",	 	 
    "GANGOTRI",
    "GANGTOK",
    "GANAPATIPULE",
    "Haora",
    "Gwalior",
    "KERALA",
    "IGATPURI",
    "IMPHAL",
    "INDORE",	 	 
    "JABALPUR",
    "JAIPUR",
    "JAISALMER",
    "JALANDHA",
    "Jabalpur",
    "Jharkhand",
    "LOTHAL",
    "LUCKNOW",
    "LUDHIANA",
    "Mumbai",
    "MaharashtraDelhi",
    "Madhya Pradesh	",
	"Maharashtra",
   	"Navi Mumbai",
    "OOTY",
    "ORCHHA",
    "OSIA",
    "Punjab",
	"Ranchi",
    "RISHYAP",
    "ROHETGARH",
    "ROURKELA",		
    "SAJAN", 
    "SALEM",
    "SAPUTARA", 
    "SASAN ",
    "SATTA",
    "Tamil Nadu",
    "Uttar Pradesh",
    "Vijayawad",
    "West Bengal",
    "YERCAUD",
    "YUKSO",
];